basicapp/urls.py
from django.conf.urls import url
from basicapp import views
app_name = 'basicapp'

urlpatterns = [

    url(r'^relative/$',views.relative,name='relative'),
    url(r'^other/$',views.other,name='other'),
    url(r'^index/$',views.index,name='index')
]

learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include
from basicapp import views

urlpatterns = [
    path('basicapp/',include('basicapp.urls')),
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),


]

basicapp/models.py
from django.db import models

# Create your models here.

basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index (request):
    cont_dict={'text':'Hello world','number':'100'}
    return render(request,'basicapp/index.html',cont_dict)
def other (request):
    return render (request,'basicapp/other.html')
def relative (request):
    return render (request,'basicapp/relative_url_templates.html')

templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

  </head>
  <body>

    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li> <a class="navbar-brand" href="{% url 'basicapp:index' %}">Brand</a> </li>
          <li> <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a> </li>
          <li> <a class="navbar-link" href="{% url 'basicapp:other' %}">Other</a> </li>

        </ul>

      </div>
    </nav>
    <div class="container">
      {% block body-block %}
      {% endblock %}

    </div>


  </body>
</html>

templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
  {% block body-block %}
  <h1>Hello from index.html</h1>
  <h1>{{ text|cut:'world' }}</h1>
  <h1>{{ number|add:'999' }}</h1>
  {% endblock %}

templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
  {% block body-block %}
  <h1>Welcome to the other</h1>
  <h2>This is example of template inheritent</h2>
  {% endblock %}

templates/basicapp/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>WELCOME to relative</h1>
    <a href="{% url 'basicapp:other' %}">The other page</a>
    <a href="{% url 'admin:index' %}">ADMIN</a>
    <a href="{% url 'index' %}">LINK  to index</a>

  </body>
</html>